### PR TITLE
Create v850.opinion

### PR DESCRIPTION
**Pull request by HexRoman**
Create opinion file for the ELF loader to recognize v850 architecture

### CODE REVIEW

**Comment by esaulenka** [comment]
Oh, again this unclear constants without good documentation...

**Comment by HexRoman** [comment]
It's the `e_machine` from the [ELF format](http://www.sco.com/developers/gabi/latest/ch4.eheader.html).

**Comment by esaulenka** [comment]
Thanks for explanation!
But have you tested this module with v800 code? As I know, it not fully compatible even with V850E (not E2) in some minor details.

**Comment by HexRoman** [comment]
Yes, I did, it works fine. I guess it's not a perfect match, but it worked good enough, and I believe it's better than nothing.

**Pull request merged**
